# Generated by Django 5.2 on 2026-04-24 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_readingprogress'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('content', models.TextField(verbose_name='مواد')),
                ('description', models.TextField(blank=True, verbose_name='تفصیل')),
                ('video_type', models.CharField(choices=[('tutorial', 'درسی ویڈیو'), ('poetry', 'شاعری'), ('story', 'کہانی'), ('music', 'موسیقی'), ('interview', 'انٹرویو'), ('other', 'دیگر')], default='other', max_length=20, verbose_name='قسم')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایاں')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='شائع ہونے کی تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='مشاہدات')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='پسندیدگی')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='تھمب نیل URL')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='میٹا عنوان')),
                ('meta_description', models.TextField(blank=True, verbose_name='میٹا تفصیل')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='میٹا کیورڈز')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.author', verbose_name='مصنف')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='زمرہ')),
            ],
            options={
                'verbose_name': 'ویڈیو',
                'verbose_name_plural': 'ویڈیوز',
                'ordering': ['-created_at'],
            },
        ),
                migrations.CreateModel(
            name='VideoPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('description', models.TextField(blank=True, verbose_name='تفصیل')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='videos/playlists/', verbose_name='سرورق')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('videos', models.ManyToManyField(related_name='playlists', to='videos.video', verbose_name='ویڈیوز')),
            ],
            options={
                'verbose_name': 'پلے لسٹ',
                'verbose_name_plural': 'پلے لسٹس',
                'ordering': ['-created_at'],
            },
        ),
            ],
        ),
    ]
