# Generated by Django 4.2.29 on 2026-03-09 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('description', models.TextField(blank=True, verbose_name='تفصیل')),
                ('video_type', models.CharField(choices=[('poetry', 'شاعری'), ('story', 'کہانی'), ('novel', 'ناول'), ('interview', 'انٹرویو'), ('documentary', 'دستاویزی'), ('other', 'دیگر')], default='poetry', max_length=20, verbose_name='ویڈیو کی قسم')),
                ('platform', models.CharField(choices=[('youtube', 'یوٹیوب'), ('vimeo', 'ویمیو'), ('dailymotion', 'ڈیلی موشن'), ('facebook', 'فیس بک'), ('local', 'مقامی')], default='youtube', max_length=20, verbose_name='پلیٹ فارم')),
                ('video_id', models.CharField(max_length=100, verbose_name='ویڈیو آئی ڈی')),
                ('video_url', models.URLField(blank=True, verbose_name='ویڈیو یو آر ایل')),
                ('thumbnail', models.ImageField(blank=True, upload_to='videos/thumbnails/', verbose_name='تھمب نیل')),
                ('duration', models.CharField(blank=True, max_length=20, verbose_name='دورانیہ')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='ٹیگز')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایاں')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='مشاہدات')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='پسندیدگی')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='شائع ہونے کی تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='میٹا عنوان')),
                ('meta_description', models.TextField(blank=True, verbose_name='میٹا تفصیل')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.author', verbose_name='مصنف')),
                ('categories', models.ManyToManyField(limit_choices_to={'category_type': 'video'}, to='core.category', verbose_name='زمرہ جات')),
            ],
            options={
                'verbose_name': 'ویڈیو',
                'verbose_name_plural': 'ویڈیوز',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('description', models.TextField(blank=True, verbose_name='تفصیل')),
                ('cover_image', models.ImageField(blank=True, upload_to='videos/playlists/', verbose_name='سرورق')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('videos', models.ManyToManyField(related_name='playlists', to='videos.video', verbose_name='ویڈیوز')),
            ],
            options={
                'verbose_name': 'پلے لسٹ',
                'verbose_name_plural': 'پلے لسٹس',
                'ordering': ['-created_at'],
            },
        ),
    ]
