# Generated by Django 4.2.29 on 2026-03-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, upload_to='videos/uploads/', verbose_name='ویڈیو فائل'),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_link',
            field=models.URLField(blank=True, verbose_name='یوٹیوب لنک'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ویڈیو آئی ڈی'),
        ),
    ]
