# Generated by Django 4.2 on 2026-04-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoplaylist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='videos/playlists/', verbose_name='سرورق'),
        ),
    ]
