# Generated by Django 4.2 on 2026-04-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_videoplaylist_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, verbose_name='تفصیل'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='نمایاں'),
        ),
        migrations.AddField(
            model_name='video',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='پسندیدگی'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='میٹا تفصیل'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='میٹا کیورڈز'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='میٹا عنوان'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, verbose_name='تھمب نیل URL'),
        ),
        migrations.AddField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('tutorial', 'درسی ویڈیو'), ('poetry', 'شاعری'), ('story', 'کہانی'), ('music', 'موسیقی'), ('interview', 'انٹرویو'), ('other', 'دیگر')], default='other', max_length=20, verbose_name='قسم'),
        ),
        migrations.AddField(
            model_name='video',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='مشاہدات'),
        ),
    ]
