# Generated by Django 4.2.29 on 2026-03-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_video_file_video_youtube_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='shares_count',
            field=models.PositiveIntegerField(default=0, verbose_name='شیئرز'),
        ),
    ]
