services:
  - type: web
    name: nawab-urdu-academy
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput --clear
    startCommand: bash start.sh
