# Generated by Django 5.2 on 2026-04-21 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایاں')),
                ('author_type', models.CharField(choices=[('classic', 'کلاسیکی شاعر'), ('female', 'شاعرات'), ('young', 'نوجوان شاعر'), ('audio', 'شاعروں کے آڈیو'), ('other', 'دیگر')], default='other', max_length=20, verbose_name='مصنف کی قسم')),
                ('bio', models.TextField(blank=True, verbose_name='تعارف')),
                ('ghazal_count', models.PositiveIntegerField(default=0, verbose_name='غزل')),
                ('nazm_count', models.PositiveIntegerField(default=0, verbose_name='نظم')),
                ('sher_count', models.PositiveIntegerField(default=0, verbose_name='شعر')),
                ('ebook_count', models.PositiveIntegerField(default=0, verbose_name='ای-کتاب')),
                ('top20_poetry_count', models.PositiveIntegerField(default=0, verbose_name='ٹاپ ٢٠ شاعری')),
                ('pictorial_poetry_count', models.PositiveIntegerField(default=0, verbose_name='تصویری شاعری')),
                ('quotes_count', models.PositiveIntegerField(default=0, verbose_name='اقوال')),
                ('videos_count', models.PositiveIntegerField(default=0, verbose_name='ویڈیوز')),
                ('qita_count', models.PositiveIntegerField(default=0, verbose_name='قطعہ')),
                ('rubai_count', models.PositiveIntegerField(default=0, verbose_name='رباعی')),
                ('qissa_count', models.PositiveIntegerField(default=0, verbose_name='قصہ')),
                ('gallery_count', models.PositiveIntegerField(default=0, verbose_name='گیلری')),
                ('blog_count', models.PositiveIntegerField(default=0, verbose_name='بلاگ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مصنف',
                'verbose_name_plural': 'مصنفین',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('category_type', models.CharField(blank=True, choices=[('novel', 'ناول'), ('story', 'کہانی'), ('poetry', 'شاعری'), ('quote', 'اقتباس'), ('blog', 'بلاگ'), ('video', 'ویڈیو')], max_length=20, null=True, verbose_name='قسم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'زمرہ',
                'verbose_name_plural': 'زمرہ جات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ای میل')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیغام')),
                ('is_read', models.BooleanField(default=False, verbose_name='پڑھا گیا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رابطہ پیغام',
                'verbose_name_plural': 'رابطہ پیغامات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logos/', verbose_name='لوگو')),
                ('alt_text', models.CharField(max_length=200, verbose_name='متبادل ٹیکسٹ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'لوگو',
                'verbose_name_plural': 'لوگوز',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ای میل')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='نام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نیوز لیٹر سبسکرائبر',
                'verbose_name_plural': 'نیوز لیٹر سبسکرائبرز',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='PremiumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='منصوبہ')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('description', models.TextField(blank=True, verbose_name='تفصیل')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='قیمت')),
                ('billing_cycle_days', models.PositiveIntegerField(default=30, verbose_name='بلنگ دن')),
                ('features', models.TextField(blank=True, verbose_name='خصوصیات')),
                ('highlight_text', models.CharField(blank=True, max_length=80, verbose_name='ہائی لائٹ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پریمیم پلان',
                'verbose_name_plural': 'پریمیم پلانز',
                'ordering': ['price', 'billing_cycle_days'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='کلید')),
                ('value', models.TextField(verbose_name='قدر')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='تفصیل')),
            ],
            options={
                'verbose_name': 'سائٹ سیٹنگ',
                'verbose_name_plural': 'سائٹ سیٹنگز',
            },
        ),
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('primary_color', models.CharField(default='#007bff', max_length=7, verbose_name='پرائمری رنگ')),
                ('background_color', models.CharField(default='#ffffff', max_length=7, verbose_name='پس منظر رنگ')),
                ('text_color', models.CharField(default='#333333', max_length=7, verbose_name='ٹیکسٹ رنگ')),
                ('font_family', models.CharField(default='Poppins, sans-serif', max_length=100, verbose_name='فونٹ فیملی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سائٹ تھیم',
                'verbose_name_plural': 'سائٹ تھیمز',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ٹیگ',
                'verbose_name_plural': 'ٹیگز',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('novel', 'ناول'), ('story', 'کہانی'), ('poetry', 'شاعری'), ('quote', 'اقتباس'), ('blog', 'بلاگ'), ('video', 'ویڈیو')], max_length=20, verbose_name='مواد کی قسم')),
                ('object_id', models.PositiveIntegerField(verbose_name='آبجیکٹ آئی ڈی')),
                ('text', models.TextField(verbose_name='تبصرہ')),
                ('is_approved', models.BooleanField(default=True, verbose_name='منظور شدہ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.comment', verbose_name='والدین')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='صارف')),
            ],
            options={
                'verbose_name': 'تبصرہ',
                'verbose_name_plural': 'تبصرے',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('content_type', models.CharField(choices=[('poetry', 'شاعری'), ('novel', 'ناول'), ('blog', 'بلاگ')], max_length=20, verbose_name='قسم')),
                ('text', models.TextField(verbose_name='متن')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='core.author', verbose_name='مصنف')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='زمرہ')),
            ],
            options={
                'verbose_name': 'مواد',
                'verbose_name_plural': 'مواد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like', 'لائک'), ('comment', 'تبصرہ'), ('follow', 'فالو'), ('membership', 'ممبرشپ'), ('system', 'سسٹم')], max_length=20, verbose_name='قسم')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('message', models.CharField(max_length=255, verbose_name='پیغام')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='لنک')),
                ('content_type', models.CharField(blank=True, choices=[('novel', 'ناول'), ('story', 'کہانی'), ('poetry', 'شاعری'), ('quote', 'اقتباس'), ('blog', 'بلاگ'), ('video', 'ویڈیو')], max_length=20, verbose_name='مواد کی قسم')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='آبجیکٹ آئی ڈی')),
                ('is_read', models.BooleanField(default=False, verbose_name='پڑھ لیا گیا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL, verbose_name='ایکٹر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='صارف')),
            ],
            options={
                'verbose_name': 'نوٹیفکیشن',
                'verbose_name_plural': 'نوٹیفکیشنز',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percent', models.PositiveIntegerField(default=0, verbose_name='پیش رفت فیصد')),
                ('last_read_at', models.DateTimeField(auto_now=True, verbose_name='آخری مطالعہ')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.chapter', verbose_name='باب')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel', verbose_name='ناول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='صارف')),
            ],
            options={
                'verbose_name': 'مطالعہ کی پیش رفت',
                'verbose_name_plural': 'مطالعہ کی پیش رفت',
                'ordering': ['-last_read_at'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('content', models.TextField(verbose_name='مواد')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='stories/covers/', verbose_name='سرورق کی تصویر')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='مشاہدات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_stories', to='core.author', verbose_name='مصنف')),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'category_type': 'story'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_story_set', to='core.category', verbose_name='زمرہ')),
            ],
            options={
                'verbose_name': 'کہانی',
                'verbose_name_plural': 'کہانیاں',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('free', 'فری'), ('active', 'فعال'), ('expired', 'ختم شدہ'), ('cancelled', 'منسوخ')], default='free', max_length=20, verbose_name='حالت')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='آغاز')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='اختتام')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='خودکار تجدید')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='نوٹس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='core.premiumplan', verbose_name='پلان')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL, verbose_name='صارف')),
            ],
            options={
                'verbose_name': 'صارف ممبرشپ',
                'verbose_name_plural': 'صارف ممبرشپس',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('novel', 'ناول'), ('story', 'کہانی'), ('poetry', 'شاعری'), ('quote', 'اقتباس'), ('blog', 'بلاگ'), ('video', 'ویڈیو')], max_length=20, verbose_name='مواد کی قسم')),
                ('object_id', models.PositiveIntegerField(verbose_name='آبجیکٹ آئی ڈی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='صارف')),
            ],
            options={
                'verbose_name': 'بک مارک',
                'verbose_name_plural': 'بک مارکس',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='ContentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('novel', 'ناول'), ('story', 'کہانی'), ('poetry', 'شاعری'), ('quote', 'اقتباس'), ('blog', 'بلاگ'), ('video', 'ویڈیو')], max_length=20, verbose_name='مواد کی قسم')),
                ('object_id', models.PositiveIntegerField(verbose_name='آبجیکٹ آئی ڈی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='صارف')),
            ],
            options={
                'verbose_name': 'پسند',
                'verbose_name_plural': 'پسندیدگیاں',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
