# Generated by Django 4.2.29 on 2026-03-09 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('bio', models.TextField(blank=True, verbose_name='سوانح حیات')),
                ('image', models.ImageField(blank=True, upload_to='authors/', verbose_name='تصویر')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پیدائش')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='تاریخ وفات')),
                ('birthplace', models.CharField(blank=True, max_length=200, verbose_name='پیدائشی مقام')),
                ('website', models.URLField(blank=True, verbose_name='ویب سائٹ')),
                ('facebook', models.URLField(blank=True, verbose_name='فیس بک')),
                ('twitter', models.URLField(blank=True, verbose_name='ٹویٹر')),
                ('instagram', models.URLField(blank=True, verbose_name='انسٹاگرام')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایاں')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='مشاہدات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مصنف',
                'verbose_name_plural': 'مصنفین',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('name_english', models.CharField(blank=True, max_length=100, verbose_name='انگریزی نام')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('category_type', models.CharField(choices=[('novel', 'ناول'), ('story', 'کہانی'), ('poetry', 'شاعری'), ('quote', 'اقتباس'), ('blog', 'بلاگ'), ('video', 'ویڈیو')], max_length=20, verbose_name='قسم')),
                ('description', models.TextField(blank=True, verbose_name='تفصیل')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='تصویر')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='رنگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'زمرہ',
                'verbose_name_plural': 'زمرہ جات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ای میل')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیغام')),
                ('is_read', models.BooleanField(default=False, verbose_name='پڑھا گیا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رابطہ پیغام',
                'verbose_name_plural': 'رابطہ پیغامات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ای میل')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='نام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نیوز لیٹر سبسکرائبر',
                'verbose_name_plural': 'نیوز لیٹر سبسکرائبرز',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='کلید')),
                ('value', models.TextField(verbose_name='قدر')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='تفصیل')),
            ],
            options={
                'verbose_name': 'سائٹ سیٹنگ',
                'verbose_name_plural': 'سائٹ سیٹنگز',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ٹیگ',
                'verbose_name_plural': 'ٹیگز',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('novel', 'ناول'), ('story', 'کہانی'), ('poetry', 'شاعری'), ('quote', 'اقتباس'), ('blog', 'بلاگ'), ('video', 'ویڈیو')], max_length=20, verbose_name='مواد کی قسم')),
                ('object_id', models.PositiveIntegerField(verbose_name='آبجیکٹ آئی ڈی')),
                ('text', models.TextField(verbose_name='تبصرہ')),
                ('is_approved', models.BooleanField(default=True, verbose_name='منظور شدہ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.comment', verbose_name='والدین')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='صارف')),
            ],
            options={
                'verbose_name': 'تبصرہ',
                'verbose_name_plural': 'تبصرے',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('novel', 'ناول'), ('story', 'کہانی'), ('poetry', 'شاعری'), ('quote', 'اقتباس'), ('blog', 'بلاگ'), ('video', 'ویڈیو')], max_length=20, verbose_name='مواد کی قسم')),
                ('object_id', models.PositiveIntegerField(verbose_name='آبجیکٹ آئی ڈی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='صارف')),
            ],
            options={
                'verbose_name': 'بک مارک',
                'verbose_name_plural': 'بک مارکس',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
