# Generated by Django 4.2.29 on 2026-03-09 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percent', models.PositiveIntegerField(default=0, verbose_name='\u067e\u06cc\u0634 \u0631\u0641\u062a \u0641\u06cc\u0635\u062f')),
                ('last_read_at', models.DateTimeField(auto_now=True, verbose_name='\u0622\u062e\u0631\u06cc \u0645\u0637\u0627\u0644\u0639\u06c1')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.chapter', verbose_name='\u0628\u0627\u0628')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel', verbose_name='\u0646\u0627\u0648\u0644')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0635\u0627\u0631\u0641')),
            ],
            options={
                'verbose_name': '\u0645\u0637\u0627\u0644\u0639\u06c1 \u06a9\u06cc \u067e\u06cc\u0634 \u0631\u0641\u062a',
                'verbose_name_plural': '\u0645\u0637\u0627\u0644\u0639\u06c1 \u06a9\u06cc \u067e\u06cc\u0634 \u0631\u0641\u062a',
                'ordering': ['-last_read_at'],
            },
        ),
    ]
