# Generated by Django 4.2 on 2026-04-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(verbose_name='مواد'),
        ),
        migrations.AlterField(
            model_name='story',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/covers/', verbose_name='سرورق کی تصویر'),
        ),
    ]
