# Generated by Django 4.2 on 2026-04-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_story_content_alter_story_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('primary_color', models.CharField(default='#007bff', max_length=7, verbose_name='پرائمری رنگ')),
                ('background_color', models.CharField(default='#ffffff', max_length=7, verbose_name='پس منظر رنگ')),
                ('text_color', models.CharField(default='#333333', max_length=7, verbose_name='ٹیکسٹ رنگ')),
                ('font_family', models.CharField(default='Poppins, sans-serif', max_length=100, verbose_name='فونٹ فیملی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سائٹ تھیم',
                'verbose_name_plural': 'سائٹ تھیمز',
            },
        ),
    ]
