# Generated by Django 4.2 on 2026-04-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(blank=True, choices=[('novel', 'ناول'), ('story', 'کہانی'), ('poetry', 'شاعری'), ('quote', 'اقتباس'), ('blog', 'بلاگ'), ('video', 'ویڈیو')], max_length=20, null=True, verbose_name='قسم'),
        ),
    ]
