# Generated by Django 4.2.29 on 2026-03-24 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_readingprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='منصوبہ')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('description', models.TextField(blank=True, verbose_name='تفصیل')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='قیمت')),
                ('billing_cycle_days', models.PositiveIntegerField(default=30, verbose_name='بلنگ دن')),
                ('features', models.TextField(blank=True, verbose_name='خصوصیات')),
                ('highlight_text', models.CharField(blank=True, max_length=80, verbose_name='ہائی لائٹ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پریمیم پلان',
                'verbose_name_plural': 'پریمیم پلانز',
                'ordering': ['price', 'billing_cycle_days'],
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('free', 'فری'), ('active', 'فعال'), ('expired', 'ختم شدہ'), ('cancelled', 'منسوخ')], default='free', max_length=20, verbose_name='حالت')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='آغاز')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='اختتام')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='خودکار تجدید')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='نوٹس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='core.premiumplan', verbose_name='پلان')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL, verbose_name='صارف')),
            ],
            options={
                'verbose_name': 'صارف ممبرشپ',
                'verbose_name_plural': 'صارف ممبرشپس',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like', 'لائک'), ('comment', 'تبصرہ'), ('follow', 'فالو'), ('membership', 'ممبرشپ'), ('system', 'سسٹم')], max_length=20, verbose_name='قسم')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('message', models.CharField(max_length=255, verbose_name='پیغام')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='لنک')),
                ('content_type', models.CharField(blank=True, choices=[('novel', 'ناول'), ('story', 'کہانی'), ('poetry', 'شاعری'), ('quote', 'اقتباس'), ('blog', 'بلاگ'), ('video', 'ویڈیو')], max_length=20, verbose_name='مواد کی قسم')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='آبجیکٹ آئی ڈی')),
                ('is_read', models.BooleanField(default=False, verbose_name='پڑھ لیا گیا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL, verbose_name='ایکٹر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='صارف')),
            ],
            options={
                'verbose_name': 'نوٹیفکیشن',
                'verbose_name_plural': 'نوٹیفکیشنز',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relationships', to=settings.AUTH_USER_MODEL, verbose_name='فالو کرنے والا')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relationships', to=settings.AUTH_USER_MODEL, verbose_name='جسے فالو کیا گیا')),
            ],
            options={
                'verbose_name': 'فالو',
                'verbose_name_plural': 'فالوز',
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='ContentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('novel', 'ناول'), ('story', 'کہانی'), ('poetry', 'شاعری'), ('quote', 'اقتباس'), ('blog', 'بلاگ'), ('video', 'ویڈیو')], max_length=20, verbose_name='مواد کی قسم')),
                ('object_id', models.PositiveIntegerField(verbose_name='آبجیکٹ آئی ڈی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='صارف')),
            ],
            options={
                'verbose_name': 'پسند',
                'verbose_name_plural': 'پسندیدگیاں',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
