# Generated by Django 4.2 on 2026-04-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, verbose_name='تعارف'),
        ),
        migrations.AddField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='author',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='نمایاں'),
        ),
    ]
