# Generated by Django 4.2 on 2026-04-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitetheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logos/', verbose_name='لوگو')),
                ('alt_text', models.CharField(max_length=200, verbose_name='متبادل ٹیکسٹ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'لوگو',
                'verbose_name_plural': 'لوگوز',
                'ordering': ['-updated_at'],
            },
        ),
    ]
