# Generated by Django 4.2.29 on 2026-03-25 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_premiumplan_usermembership_notification_userfollow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_followers', to='core.author', verbose_name='مصنف')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_follow_relationships', to=settings.AUTH_USER_MODEL, verbose_name='فالو کرنے والا')),
            ],
            options={
                'verbose_name': 'مصنف فالو',
                'verbose_name_plural': 'مصنف فالوز',
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'author')},
            },
        ),
    ]
