# Generated by Django 6.0.4 on 2026-04-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_type',
            field=models.CharField(choices=[('classic', 'کلاسیکی شاعر'), ('female', 'شاعرات'), ('young', 'نوجوان شاعر'), ('audio', 'شاعروں کے آڈیو'), ('other', 'دیگر')], default='other', max_length=20, verbose_name='مصنف کی قسم'),
        ),
        migrations.AddField(
            model_name='author',
            name='blog_count',
            field=models.PositiveIntegerField(default=0, verbose_name='بلاگ'),
        ),
        migrations.AddField(
            model_name='author',
            name='ebook_count',
            field=models.PositiveIntegerField(default=0, verbose_name='ای-کتاب'),
        ),
        migrations.AddField(
            model_name='author',
            name='gallery_count',
            field=models.PositiveIntegerField(default=0, verbose_name='گیلری'),
        ),
        migrations.AddField(
            model_name='author',
            name='ghazal_count',
            field=models.PositiveIntegerField(default=0, verbose_name='غزل'),
        ),
        migrations.AddField(
            model_name='author',
            name='nazm_count',
            field=models.PositiveIntegerField(default=0, verbose_name='نظم'),
        ),
        migrations.AddField(
            model_name='author',
            name='pictorial_poetry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تصویری شاعری'),
        ),
        migrations.AddField(
            model_name='author',
            name='qissa_count',
            field=models.PositiveIntegerField(default=0, verbose_name='قصہ'),
        ),
        migrations.AddField(
            model_name='author',
            name='qita_count',
            field=models.PositiveIntegerField(default=0, verbose_name='قطعہ'),
        ),
        migrations.AddField(
            model_name='author',
            name='quotes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='اقوال'),
        ),
        migrations.AddField(
            model_name='author',
            name='rubai_count',
            field=models.PositiveIntegerField(default=0, verbose_name='رباعی'),
        ),
        migrations.AddField(
            model_name='author',
            name='sher_count',
            field=models.PositiveIntegerField(default=0, verbose_name='شعر'),
        ),
        migrations.AddField(
            model_name='author',
            name='top20_poetry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='ٹاپ ٢٠ شاعری'),
        ),
        migrations.AddField(
            model_name='author',
            name='videos_count',
            field=models.PositiveIntegerField(default=0, verbose_name='ویڈیوز'),
        ),
    ]
