# Generated by Django 4.2.29 on 2026-03-31 10:55

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_authorfollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='مواد')),
                ('cover_image', models.ImageField(blank=True, upload_to='stories/covers/', verbose_name='سرورق کی تصویر')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='مشاہدات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_stories', to='core.author', verbose_name='مصنف')),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'category_type': 'story'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_story_set', to='core.category', verbose_name='زمرہ')),
            ],
            options={
                'verbose_name': 'کہانی',
                'verbose_name_plural': 'کہانیاں',
                'ordering': ['-created_at'],
            },
        ),
    ]
