# Generated by Django 4.2.29 on 2026-04-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_story'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollow',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userfollow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='userfollow',
            name='following',
        ),
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='author',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='author',
            name='birthplace',
        ),
        migrations.RemoveField(
            model_name='author',
            name='death_date',
        ),
        migrations.RemoveField(
            model_name='author',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
        migrations.RemoveField(
            model_name='author',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='author',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='author',
            name='views_count',
        ),
        migrations.RemoveField(
            model_name='author',
            name='website',
        ),
        migrations.DeleteModel(
            name='AuthorFollow',
        ),
        migrations.DeleteModel(
            name='UserFollow',
        ),
    ]
