# Generated by Django 4.2.29 on 2026-04-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userfollow_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='نمایاں'),
        ),
    ]
