# Generated by Django 4.2.29 on 2026-04-08 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_author_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('content_type', models.CharField(choices=[('poetry', 'شاعری'), ('novel', 'ناول'), ('blog', 'بلاگ')], max_length=20, verbose_name='قسم')),
                ('text', models.TextField(verbose_name='متن')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='core.author', verbose_name='مصنف')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='زمرہ')),
            ],
            options={
                'verbose_name': 'مواد',
                'verbose_name_plural': 'مواد',
                'ordering': ['-created_at'],
            },
        ),
    ]
