# Generated by Django 4.2.29 on 2026-03-09 17:35

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='مواد')),
                ('excerpt', models.TextField(blank=True, verbose_name='خلاصہ')),
                ('featured_image', models.ImageField(blank=True, upload_to='stories/', verbose_name='نمایاں تصویر')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='ٹیگز')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایاں')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='مشاہدات')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='پسندیدگی')),
                ('reading_time', models.PositiveIntegerField(default=0, verbose_name='پڑھنے کا وقت (منٹ)')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='شائع ہونے کی تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='میٹا عنوان')),
                ('meta_description', models.TextField(blank=True, verbose_name='میٹا تفصیل')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='میٹا کی ورڈز')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='core.author', verbose_name='مصنف')),
                ('categories', models.ManyToManyField(limit_choices_to={'category_type': 'story'}, to='core.category', verbose_name='زمرہ جات')),
            ],
            options={
                'verbose_name': 'کہانی',
                'verbose_name_plural': 'کہانیاں',
                'ordering': ['-created_at'],
            },
        ),
    ]
