# Generated by Django 4.2 on 2026-04-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='excerpt',
            field=models.CharField(blank=True, max_length=500, verbose_name='خلاصہ'),
        ),
        migrations.AddField(
            model_name='story',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='stories/featured/', verbose_name='نمایاں تصویر'),
        ),
        migrations.AddField(
            model_name='story',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='نمایاں'),
        ),
        migrations.AddField(
            model_name='story',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='پسندیدگی'),
        ),
        migrations.AddField(
            model_name='story',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='میٹا تفصیل'),
        ),
        migrations.AddField(
            model_name='story',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='میٹا کی ورڈز'),
        ),
        migrations.AddField(
            model_name='story',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='میٹا عنوان'),
        ),
        migrations.AddField(
            model_name='story',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اشاعت'),
        ),
        migrations.AddField(
            model_name='story',
            name='reading_time',
            field=models.PositiveIntegerField(default=0, verbose_name='پڑھنے کا وقت (منٹ)'),
        ),
        migrations.AddField(
            model_name='story',
            name='shares_count',
            field=models.PositiveIntegerField(default=0, verbose_name='شیئرز'),
        ),
        migrations.AddField(
            model_name='story',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='story',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='مشاہدات'),
        ),
    ]
