# Generated by Django 4.2 on 2026-04-17 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_content'),
        ('stories', '0002_story_shares_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.author', verbose_name='مصنف'),
        ),
        migrations.AlterField(
            model_name='story',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اشاعت'),
        ),
    ]
