# Generated by Django 4.2.29 on 2026-03-09 17:40

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ای میل')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='ظاہری نام')),
                ('bio', models.TextField(blank=True, verbose_name='سوانح حیات')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='اوتار')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='فون نمبر')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'خاتون'), ('other', 'دیگر')], max_length=10, verbose_name='جنس')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پیدائش')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='شہر')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='ملک')),
                ('website', models.URLField(blank=True, verbose_name='ویب سائٹ')),
                ('facebook', models.URLField(blank=True, verbose_name='فیس بک')),
                ('twitter', models.URLField(blank=True, verbose_name='ٹویٹر')),
                ('instagram', models.URLField(blank=True, verbose_name='انسٹاگرام')),
                ('is_author', models.BooleanField(default=False, verbose_name='مصنف')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تصدیق شدہ')),
                ('dark_mode', models.BooleanField(default=False, verbose_name='ڈارک موڈ')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='ای میل نوٹیفکیشنز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'صارف',
                'verbose_name_plural': 'صارفین',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'لاگ ان'), ('logout', 'لاگ آؤٹ'), ('view', 'مشاہدہ'), ('bookmark', 'بک مارک'), ('comment', 'تبصرہ'), ('share', 'شیئر')], max_length=20, verbose_name='سرگرمی کی قسم')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='تفصیل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آئی پی ایڈریس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='صارف')),
            ],
            options={
                'verbose_name': 'صارف کی سرگرمی',
                'verbose_name_plural': 'صارفین کی سرگرمیاں',
                'ordering': ['-created_at'],
            },
        ),
    ]
