# Generated by Django 4.2 on 2026-04-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('description', models.TextField(blank=True, verbose_name='تفصیل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بلاگ زمرہ',
                'verbose_name_plural': 'بلاگ زمرہ جات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('content', models.TextField(verbose_name='مواد')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='شائع ہونے کی تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='core.author', verbose_name='مصنف')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='زمرہ')),
            ],
            options={
                'verbose_name': 'بلاگ پوسٹ',
                'verbose_name_plural': 'بلاگ پوسٹس',
                'ordering': ['-created_at'],
            },
        ),
    ]
