# Generated by Django 4.2.29 on 2026-03-09 17:40

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('description', models.TextField(blank=True, verbose_name='تفصیل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بلاگ زمرہ',
                'verbose_name_plural': 'بلاگ زمرہ جات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('excerpt', models.TextField(blank=True, verbose_name='خلاصہ')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='مواد')),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/', verbose_name='نمایاں تصویر')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='ٹیگز')),
                ('status', models.CharField(choices=[('draft', 'ڈرافٹ'), ('published', 'شائع شدہ'), ('archived', 'محفوظ شدہ')], default='draft', max_length=20, verbose_name='حالت')),
                ('is_published', models.BooleanField(default=False, verbose_name='شائع شدہ')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایاں')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='مشاہدات')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='پسندیدگی')),
                ('reading_time', models.PositiveIntegerField(default=0, verbose_name='پڑھنے کا وقت (منٹ)')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='شائع ہونے کی تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='میٹا عنوان')),
                ('meta_description', models.TextField(blank=True, verbose_name='میٹا تفصیل')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='میٹا کی ورڈز')),
                ('canonical_url', models.URLField(blank=True, verbose_name='کینونیکل یو آر ایل')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='core.author', verbose_name='مصنف')),
                ('categories', models.ManyToManyField(limit_choices_to={'category_type': 'blog'}, to='core.category', verbose_name='زمرہ جات')),
            ],
            options={
                'verbose_name': 'بلاگ پوسٹ',
                'verbose_name_plural': 'بلاگ پوسٹس',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
