# Generated by Django 4.2.29 on 2026-03-09 17:32

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='تفصیل')),
                ('cover_image', models.ImageField(upload_to='novels/covers/', verbose_name='سرورق کی تصویر')),
                ('status', models.CharField(choices=[('ongoing', 'جاری'), ('completed', 'مکمل'), ('hiatus', 'تعطل')], default='ongoing', max_length=20, verbose_name='حالت')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایاں')),
                ('is_premium', models.BooleanField(default=False, verbose_name='پریمیم')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='مشاہدات')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='پسندیدگی')),
                ('total_chapters', models.PositiveIntegerField(default=0, verbose_name='کل ابواب')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='شائع ہونے کی تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='میٹا عنوان')),
                ('meta_description', models.TextField(blank=True, verbose_name='میٹا تفصیل')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='میٹا کی ورڈز')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novels', to='core.author', verbose_name='مصنف')),
                ('categories', models.ManyToManyField(limit_choices_to={'category_type': 'novel'}, to='core.category', verbose_name='زمرہ جات')),
            ],
            options={
                'verbose_name': 'ناول',
                'verbose_name_plural': 'ناولز',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NovelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='ریٹنگ')),
                ('review_text', models.TextField(verbose_name='جائزہ')),
                ('is_approved', models.BooleanField(default=True, verbose_name='منظور شدہ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='novels.novel', verbose_name='ناول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='صارف')),
            ],
            options={
                'verbose_name': 'جائزہ',
                'verbose_name_plural': 'جائزے',
                'ordering': ['-created_at'],
                'unique_together': {('novel', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField(verbose_name='باب نمبر')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(verbose_name='سلگ')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='مواد')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('is_premium', models.BooleanField(default=False, verbose_name='پریمیم')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='مشاہدات')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='الفاظ کی تعداد')),
                ('reading_time', models.PositiveIntegerField(default=0, verbose_name='پڑھنے کا وقت (منٹ)')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='شائع ہونے کی تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='میٹا عنوان')),
                ('meta_description', models.TextField(blank=True, verbose_name='میٹا تفصیل')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novels.novel', verbose_name='ناول')),
            ],
            options={
                'verbose_name': 'باب',
                'verbose_name_plural': 'ابواب',
                'ordering': ['chapter_number'],
                'unique_together': {('novel', 'chapter_number')},
            },
        ),
    ]
