# Generated by Django 5.2 on 2026-04-21 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('content', models.TextField(verbose_name='مواد')),
                ('total_chapters', models.PositiveIntegerField(default=0, verbose_name='کل ابواب')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='شائع ہونے کی تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novels', to='core.author', verbose_name='مصنف')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='زمرہ')),
            ],
            options={
                'verbose_name': 'ناول',
                'verbose_name_plural': 'ناولز',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField(verbose_name='باب نمبر')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(verbose_name='سلگ')),
                ('content', models.TextField(verbose_name='مواد')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('is_premium', models.BooleanField(default=False, verbose_name='پریمیم')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='مشاہدات')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='الفاظ کی تعداد')),
                ('reading_time', models.PositiveIntegerField(default=0, verbose_name='پڑھنے کا وقت (منٹ)')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='شائع ہونے کی تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='میٹا عنوان')),
                ('meta_description', models.TextField(blank=True, verbose_name='میٹا تفصیل')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novels.novel', verbose_name='ناول')),
            ],
            options={
                'verbose_name': 'باب',
                'verbose_name_plural': 'ابواب',
                'ordering': ['chapter_number'],
                'unique_together': {('novel', 'chapter_number')},
            },
        ),
        migrations.CreateModel(
            name='NovelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='ریٹنگ')),
                ('review_text', models.TextField(verbose_name='جائزہ')),
                ('is_approved', models.BooleanField(default=True, verbose_name='منظور شدہ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='novels.novel', verbose_name='ناول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='صارف')),
            ],
            options={
                'verbose_name': 'جائزہ',
                'verbose_name_plural': 'جائزے',
                'ordering': ['-created_at'],
                'unique_together': {('novel', 'user')},
            },
        ),
    ]
