# Generated by Django 4.2.29 on 2026-03-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='novels/pdfs/', verbose_name='پی ڈی ایف فائل'),
        ),
    ]
