# Generated by Django 4.2.29 on 2026-03-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_novel_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='shares_count',
            field=models.PositiveIntegerField(default=0, verbose_name='شیئرز'),
        ),
    ]
