# Generated by Django 4.2 on 2026-04-18 11:52

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0003_alter_novel_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter_number'], 'verbose_name': 'باب', 'verbose_name_plural': 'ابواب'},
        ),
        migrations.AlterModelOptions(
            name='novel',
            options={'ordering': ['-created_at'], 'verbose_name': 'ناول', 'verbose_name_plural': 'ناولز'},
        ),
        migrations.AlterModelOptions(
            name='novelreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'جائزہ', 'verbose_name_plural': 'جائزے'},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.PositiveIntegerField(verbose_name='باب نمبر'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='مواد'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='پریمیم'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='شائع شدہ'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='میٹا تفصیل'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='میٹا عنوان'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novels.novel', verbose_name='ناول'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='شائع ہونے کی تاریخ'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='reading_time',
            field=models.PositiveIntegerField(default=0, verbose_name='پڑھنے کا وقت (منٹ)'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(verbose_name='سلگ'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='مشاہدات'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='word_count',
            field=models.PositiveIntegerField(default=0, verbose_name='الفاظ کی تعداد'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novels', to='core.author', verbose_name='مصنف'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='زمرہ'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='content',
            field=models.TextField(verbose_name='مواد'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='شائع شدہ'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='شائع ہونے کی تاریخ'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='سلگ'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='novelreview',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='منظور شدہ'),
        ),
        migrations.AlterField(
            model_name='novelreview',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='novels.novel', verbose_name='ناول'),
        ),
        migrations.AlterField(
            model_name='novelreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='ریٹنگ'),
        ),
        migrations.AlterField(
            model_name='novelreview',
            name='review_text',
            field=models.TextField(verbose_name='جائزہ'),
        ),
        migrations.AlterField(
            model_name='novelreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='صارف'),
        ),
    ]
