# Generated by Django 4.2.29 on 2026-03-31 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_story'),
        ('novels', '0003_novel_shares_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='categories',
        ),
        migrations.AddField(
            model_name='novel',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_type': 'novel'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='زمرہ'),
        ),
    ]
