# Generated by Django 4.2 on 2026-04-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_alter_chapter_options_alter_novel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(verbose_name='مواد'),
        ),
    ]
