# Generated by Django 4.2 on 2026-04-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_alter_chapter_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='total_chapters',
            field=models.PositiveIntegerField(default=0, verbose_name='کل ابواب'),
        ),
    ]
