# Generated by Django 4.2.29 on 2026-03-09 17:37

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('poetry_type', models.CharField(choices=[('ghazal', 'غزل'), ('nazm', 'نظم'), ('shayari', 'شاعری'), ('rubai', 'رباعی'), ('qata', 'قطعہ'), ('marsiya', 'مرثیہ'), ('manqabat', 'منقبت'), ('naat', 'نعت')], default='ghazal', max_length=20, verbose_name='شاعری کی قسم')),
                ('mood', models.CharField(blank=True, choices=[('love', 'محبت'), ('sad', 'اداسی'), ('romantic', 'رومانوی'), ('inspirational', 'حوصلہ افزائی'), ('religious', 'مذہبی'), ('patriotic', 'وطن دوستی'), ('funny', 'مزاحیہ'), ('philosophical', 'فلسفیانہ')], max_length=20, verbose_name='جذبہ')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='اشعار')),
                ('background_image', models.ImageField(blank=True, upload_to='poetry/backgrounds/', verbose_name='پس منظر کی تصویر')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='ٹیگز')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایاں')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='مشاہدات')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='پسندیدگی')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='شائع ہونے کی تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='میٹا عنوان')),
                ('meta_description', models.TextField(blank=True, verbose_name='میٹا تفصیل')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='میٹا کی ورڈز')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poetry', to='core.author', verbose_name='شاعر')),
                ('categories', models.ManyToManyField(limit_choices_to={'category_type': 'poetry'}, to='core.category', verbose_name='زمرہ جات')),
            ],
            options={
                'verbose_name': 'شاعری',
                'verbose_name_plural': 'اشعار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoetryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('description', models.TextField(blank=True, verbose_name='تفصیل')),
                ('cover_image', models.ImageField(blank=True, upload_to='poetry/collections/', verbose_name='سرورق')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='core.author', verbose_name='شاعر')),
                ('poems', models.ManyToManyField(related_name='collections', to='poetry.poetry', verbose_name='اشعار')),
            ],
            options={
                'verbose_name': 'کلیہ اشعار',
                'verbose_name_plural': 'کلیات اشعار',
                'ordering': ['-created_at'],
            },
        ),
    ]
