# Generated by Django 4.2.29 on 2026-03-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poetry',
            name='shares_count',
            field=models.PositiveIntegerField(default=0, verbose_name='شیئرز'),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='poetry/backgrounds/', verbose_name='پس منظر'),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='mood',
            field=models.CharField(blank=True, choices=[('love', 'محبت'), ('sad', 'اداسی'), ('romantic', 'رومانوی'), ('inspirational', 'حوصلہ افزائی'), ('religious', 'مذہبی'), ('patriotic', 'وطن دوستی'), ('funny', 'مزاحیہ'), ('philosophical', 'فلسفیانہ')], max_length=20, verbose_name='موڈ'),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='poetry_type',
            field=models.CharField(choices=[('ghazal', 'غزل'), ('nazm', 'نظم'), ('shayari', 'شاعری'), ('rubai', 'رباعی'), ('qata', 'قطعہ'), ('marsiya', 'مرثیہ'), ('manqabat', 'منقبت'), ('naat', 'نعت')], default='ghazal', max_length=20, verbose_name='قسم'),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اشاعت'),
        ),
    ]
