# Generated by Django 4.2 on 2026-04-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poetry',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='شائع ہونے کی تاریخ'),
        ),
    ]
