# Generated by Django 5.2 on 2026-04-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poetry',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='پسندیدگی'),
        ),
        migrations.AddField(
            model_name='poetry',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='مشاہدات'),
        ),
    ]
