# Generated by Django 5.2 on 2026-04-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0001_initial'),
    ]

    operations = [
    ]
