# Generated by Django 5.2 on 2026-04-24 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_readingprogress'),
        ('poetry', '0002_sync_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poetry',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poetry', to='core.author', verbose_name='مصنف'),
        ),
    ]
