# Generated by Django 5.0.14 on 2026-04-14 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_content'),
        ('poetry', '0003_remove_poetry_categories_poetry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poetry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.author', verbose_name='مصنف'),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_type': 'poetry'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poetry_set', to='core.category', verbose_name='زمرہ'),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='SEO Keywords'),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='SEO Title'),
        ),
    ]
