# Generated by Django 4.2.29 on 2026-03-09 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='اقتباس')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('quote_type', models.CharField(choices=[('islamic', 'اسلامی'), ('motivational', 'حوصلہ افزائی'), ('love', 'محبت'), ('life', 'زندگی'), ('friendship', 'دوستی'), ('success', 'کامیابی'), ('wisdom', 'دانش'), ('funny', 'مزاحیہ'), ('sad', 'اداسی'), ('poetry', 'شاعری')], default='motivational', max_length=20, verbose_name='اقتباس کی قسم')),
                ('background_image', models.ImageField(blank=True, upload_to='quotes/backgrounds/', verbose_name='پس منظر کی تصویر')),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='متن کا رنگ')),
                ('background_color', models.CharField(default='#1a1a2e', max_length=7, verbose_name='پس منظر کا رنگ')),
                ('font_size', models.PositiveSmallIntegerField(default=24, verbose_name='فونٹ سائز')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='ٹیگز')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایاں')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='مشاہدات')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='پسندیدگی')),
                ('shares_count', models.PositiveIntegerField(default=0, verbose_name='شیئرز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='میٹا عنوان')),
                ('meta_description', models.TextField(blank=True, verbose_name='میٹا تفصیل')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.author', verbose_name='مصنف')),
                ('categories', models.ManyToManyField(limit_choices_to={'category_type': 'quote'}, to='core.category', verbose_name='زمرہ جات')),
            ],
            options={
                'verbose_name': 'اقتباس',
                'verbose_name_plural': 'اقتباسات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('description', models.TextField(blank=True, verbose_name='تفصیل')),
                ('cover_image', models.ImageField(blank=True, upload_to='quotes/collections/', verbose_name='سرورق')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotes', models.ManyToManyField(related_name='collections', to='quotes.quote', verbose_name='اقتباسات')),
            ],
            options={
                'verbose_name': 'اقتباسات کا مجموعہ',
                'verbose_name_plural': 'اقتباسات کے مجموعے',
                'ordering': ['-created_at'],
            },
        ),
    ]
