# Generated by Django 5.2 on 2026-04-24 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_readingprogress'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('text', models.TextField(verbose_name='مواد')),
                ('quote_type', models.CharField(choices=[('general', 'عام'), ('islamic', 'اسلامی'), ('motivational', 'ح副总 / مشوق'), ('poetic', 'شاعری'), ('romantic', 'رومانی'), ('philosophical', 'فلسفیانہ'), ('wisdom', 'حکمت'), ('friendship', 'دوستی'), ('life', 'زندگی'), ('success', 'کامیابی')], default='general', max_length=20, verbose_name='قسم')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایں')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='شائع ہونے کی تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='مشاہدات')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='پسندیدگی')),
                ('shares_count', models.PositiveIntegerField(default=0, verbose_name='شیئرز')),
                ('meta_title', models.CharField(blank=True, default='', max_length=200, verbose_name='میٹا عنوان')),
                ('meta_description', models.TextField(blank=True, default='', verbose_name='میٹا تفصیل')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='quotes/backgrounds/', verbose_name='پس منظر کی تصویر')),
                ('text_color', models.CharField(blank=True, default='#000000', max_length=20, verbose_name='متن کا رنگ')),
                ('background_color', models.CharField(blank=True, default='#FFFFFF', max_length=20, verbose_name='پس منظر کا رنگ')),
                ('font_size', models.PositiveIntegerField(default=18, verbose_name='فونٹ سائز')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.author', verbose_name='مصنف')),
                ('categories', models.ManyToManyField(blank=True, related_name='quote_categories', to='core.category', verbose_name='زمرہ جات')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='زمرہ')),
            ],
            options={
                'verbose_name': 'اقتباس',
                'verbose_name_plural': 'اقتباسات',
            },
        ),
                migrations.CreateModel(
            name='QuoteCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='سلگ')),
                ('description', models.TextField(blank=True, verbose_name='تفصیل')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='quotes/collections/', verbose_name='سرورق')),
                ('is_published', models.BooleanField(default=True, verbose_name='شائع شدہ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotes', models.ManyToManyField(related_name='collections', to='quotes.quote', verbose_name='اقتباسات')),
            ],
            options={
                'verbose_name': 'اقتباسات کا مجموعہ',
                'verbose_name_plural': 'اقتباسات کے مجموعے',
                'ordering': ['-created_at'],
            },
        ),
            ],
        ),
    ]
