# Generated by Django 5.0.14 on 2026-04-08 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_author_is_featured'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='میٹا کی ورڈز'),
        ),
        migrations.AddField(
            model_name='quote',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اشاعت'),
        ),
        migrations.AddField(
            model_name='quote',
            name='title',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.author', verbose_name='مصنف'),
        ),
    ]
