# Generated by Django 4.2.29 on 2026-04-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_author_bio_author_is_active_author_is_featured'),
        ('quotes', '0002_quote_published_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='quote',
            name='background_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=20, verbose_name='پس منظر کا رنگ'),
        ),
        migrations.AddField(
            model_name='quote',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='quotes/backgrounds/', verbose_name='پس منظر کی تصویر'),
        ),
        migrations.AddField(
            model_name='quote',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='quote_categories', to='core.category', verbose_name='زمرہ جات'),
        ),
        migrations.AddField(
            model_name='quote',
            name='font_size',
            field=models.PositiveIntegerField(default=18, verbose_name='فونٹ سائز'),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='نمایں'),
        ),
        migrations.AddField(
            model_name='quote',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='پسندیدگی'),
        ),
        migrations.AddField(
            model_name='quote',
            name='meta_description',
            field=models.TextField(blank=True, default='', verbose_name='میٹا تفصیل'),
        ),
        migrations.AddField(
            model_name='quote',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='میٹا عنوان'),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_type',
            field=models.CharField(choices=[('general', 'عام'), ('islamic', 'اسلامی'), ('motivational', 'ح副总 / مشوق'), ('poetic', 'شاعری'), ('romantic', 'رومانی'), ('philosophical', 'فلسفیانہ'), ('wisdom', 'حکمت'), ('friendship', 'دوستی'), ('life', 'زندگی'), ('success', 'کامیابی')], default='general', max_length=20, verbose_name='قسم'),
        ),
        migrations.AddField(
            model_name='quote',
            name='shares_count',
            field=models.PositiveIntegerField(default=0, verbose_name='شیئرز'),
        ),
        migrations.AddField(
            model_name='quote',
            name='text_color',
            field=models.CharField(blank=True, default='#000000', max_length=20, verbose_name='متن کا رنگ'),
        ),
        migrations.AddField(
            model_name='quote',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='مشاہدات'),
        ),
    ]
